from __future__ import annotations

from dataclasses import dataclass
from typing import Final


@dataclass(frozen=True)
class RevenueProjectionAssumptions:
    # Number of monthly rows to generate for synthetic projections.
    projection_months: int = 36
    # Optional YYYY-MM override for baseline month from observed daily sales.
    # If None, the latest month in observed data is used.
    baseline_month: str | None = None
    # Calendar month to start synthetic output (YYYY-MM).
    projection_start_month: str = "2026-03"
    # Number of historical years used when computing monthly seasonality factors.
    seasonality_lookback_years: int = 10
    # Annual CAGR applied to marketplace sales trajectory (Year 2-3).
    sales_cagr: float = 0.03
    # Annual inflation-style growth rate applied to average selling price.
    avg_sell_price_annual_growth: float = 0.03
    # Standard deviation for monthly random noise in synthetic generation.
    jitter_std: float = 0.05
    # Marketplace fee rate applied to GMV.
    take_rate: float = 0.02
    # Lower bound for monthly transaction count in Year 2-3.
    year2_3_min_txns: int = 10
    # Upper bound for monthly transaction count in Year 2-3.
    year2_3_max_txns: int = 400
    # Monthly USD price for paid subscriptions.
    subscription_price_usd: float = 20.0
    # New users in the first projected cohort month.
    new_users_start: float = 700.0
    # Monthly new-user growth rate applied in Year 1.
    new_users_monthly_growth_year1: float = 0.10
    # Monthly new-user growth rate applied in Year 2.
    new_users_monthly_growth_year2: float = 0.05
    # Monthly new-user growth rate applied in Year 3.
    new_users_monthly_growth_year3: float = 0.03
    # Extra acquisition boost applied in November and December.
    new_user_holiday_spike_multiplier: float = 1.30
    # Share of a cohort still active one month after signup.
    user_retention_month_1: float = 0.25
    # Share of a cohort still active two months after signup.
    user_retention_month_2: float = 0.12
    # Share of a cohort still active three months after signup.
    user_retention_month_3: float = 0.05
    # Monthly decay applied to cohort retention after Month 3.
    user_retention_decay: float = 0.97
    # Initial MAU->paid conversion rate.
    subscription_conversion_start: float = 0.008
    # Target MAU->paid conversion rate approached over time.
    subscription_conversion_end: float = 0.025
    # Share of the remaining conversion-rate gap closed each month.
    subscription_conversion_monthly_improvement_rate: float = 0.08
    # Initial monthly paid-subscriber retention rate.
    subscription_retention_start: float = 0.3
    # Target monthly paid-subscriber retention rate approached over time.
    subscription_retention_end: float = 0.6
    # Share of the remaining retention-rate gap closed each month.
    subscription_retention_monthly_improvement_rate: float = 0.06
    # Monthly sessions generated by each monthly active user.
    sessions_per_mau: float = 3.0
    # Average pageviews generated in each session.
    pageviews_per_session: float = 5.0
    # Share of pageviews that convert into a CPA-qualified action.
    ad_action_rate_per_pageview: float = 0.003
    # USD payout per ad action.
    ad_cpa_usd: float = 3.0
    # Starting R2 object storage footprint in GB.
    r2_storage_start_gb: float = 100.0
    # Target R2 object storage footprint by the end of the projection in GB.
    r2_storage_target_end_gb: float = 5000.0
    # Cloudflare R2 standard storage price per GB-month in USD.
    r2_storage_price_per_gb_month: float = 0.015
    # Free R2 storage included each month in GB.
    r2_storage_free_gb: float = 10.0
    # Estimated R2 Class A operations generated by each new user.
    r2_class_a_ops_per_new_user: float = 20.0
    # Cloudflare R2 Class A request price per million operations in USD.
    r2_class_a_price_per_million: float = 4.5
    # Estimated R2 Class B operations generated by each pageview.
    r2_class_b_ops_per_pageview: float = 6.0
    # Cloudflare R2 Class B request price per million operations in USD.
    r2_class_b_price_per_million: float = 0.36
    # Managed Postgres platform plan cost in USD per month.
    postgres_base_plan_monthly_usd: float = 25.0
    # Managed Postgres micro compute price in USD per month.
    postgres_micro_compute_monthly_usd: float = 10.0
    # Managed Postgres small compute price in USD per month.
    postgres_small_compute_monthly_usd: float = 15.0
    # Managed Postgres medium compute price in USD per month.
    postgres_medium_compute_monthly_usd: float = 60.0
    # MAU threshold for scaling Postgres from micro to small compute.
    postgres_small_mau_threshold: int = 25000
    # MAU threshold for scaling Postgres from small to medium compute.
    postgres_medium_mau_threshold: int = 100000
    # MAU threshold for adding one read-only Postgres replica.
    postgres_read_replica_mau_threshold: int = 150000
    # Included Postgres disk allocation before overage pricing in GB.
    postgres_disk_base_gb: float = 8.0
    # Additional Postgres disk consumed per 1,000 cumulative new users in GB.
    postgres_disk_gb_per_1000_cumulative_new_users: float = 1.0
    # Managed Postgres disk overage price per GB-month in USD.
    postgres_disk_price_per_gb_month: float = 0.125
    # Monthly Cloudflare Pages hosting cost in USD.
    cloudflare_pages_monthly_usd: float = 0.0
    # Base monthly Cloudflare Workers paid-plan cost in USD.
    workers_base_monthly_usd: float = 5.0
    # Included Workers requests per month in millions.
    workers_included_requests_millions: float = 10.0
    # Workers request overage price per million requests in USD.
    workers_request_price_per_million: float = 0.30
    # Included Workers CPU time per month in million milliseconds.
    workers_included_cpu_million_ms: float = 30.0
    # Workers CPU overage price per million milliseconds in USD.
    workers_cpu_price_per_million_ms: float = 0.02
    # Estimated Workers requests generated by each pageview.
    workers_requests_per_pageview: float = 0.35
    # Estimated Workers requests generated by each new user.
    workers_requests_per_new_user: float = 12.0
    # Average CPU milliseconds consumed per Workers request.
    workers_avg_cpu_ms_per_request: float = 15.0
    # Flat monthly transactional email SaaS cost in USD.
    transactional_email_monthly_usd: float = 30.0
    # Monthly dedicated residential/static proxy cost in USD.
    scraper_proxy_monthly_usd: float = 35.0
    # Monthly Instagram marketing budget in Year 1.
    instagram_marketing_monthly_year1: float = 1500.0
    # Monthly Instagram marketing budget in Year 2.
    instagram_marketing_monthly_year2: float = 2500.0
    # Monthly Instagram marketing budget in Year 3.
    instagram_marketing_monthly_year3: float = 3500.0
    # Monthly Twitter/X marketing budget in Year 1.
    twitter_marketing_monthly_year1: float = 500.0
    # Monthly Twitter/X marketing budget in Year 2.
    twitter_marketing_monthly_year2: float = 750.0
    # Monthly Twitter/X marketing budget in Year 3.
    twitter_marketing_monthly_year3: float = 1000.0
    # Monthly Facebook marketing budget in Year 1.
    facebook_marketing_monthly_year1: float = 1000.0
    # Monthly Facebook marketing budget in Year 2.
    facebook_marketing_monthly_year2: float = 1500.0
    # Monthly Facebook marketing budget in Year 3.
    facebook_marketing_monthly_year3: float = 2000.0
    # Monthly content-creation and graphics budget in Year 1.
    content_creation_monthly_year1: float = 800.0
    # Monthly content-creation and graphics budget in Year 2.
    content_creation_monthly_year2: float = 1200.0
    # Monthly content-creation and graphics budget in Year 3.
    content_creation_monthly_year3: float = 1500.0
    # Team size in Year 1, used for software-seat sizing only.
    team_size_year1: int = 2
    # Team size in Year 2, used for software-seat sizing only.
    team_size_year2: int = 2
    # Team size in Year 3, used for software-seat sizing only.
    team_size_year3: int = 3
    # Combined monthly software-tools cost per team member in USD.
    software_tools_per_team_member_monthly_usd: float = 15.75
    # One-time incorporation/setup cost in USD.
    incorporation_setup_usd: float = 500.0
    # Random seed for deterministic synthetic output.
    seed: int = 42


@dataclass(frozen=True)
class MauProjectionAssumptions:
    # External reference URL for Chrono24 monthly traffic series.
    semrush_chrono24_url: str = "https://www.semrush.com/website/chrono24.com/overview/"
    # Year-1 target MAU trajectory (12 monthly anchor points).
    year1_mau_trajectory: tuple[int, ...] = (
        300,
        800,
        1500,
        2200,
        3500,
        5000,
        7500,
        10000,
        13000,
        17000,
        22000,
        28000,
    )
    # Scalar applied to the Year-1 MAU trajectory for conservative/aggressive cases.
    year1_mau_scale: float = 0.80
    # Annual CAGR used for benchmark traffic extrapolation.
    benchmark_traffic_cagr: float = 0.02
    # MAU threshold to activate marketplace fee switch in growth model.
    fee_switch_mau_threshold: float = 12000.0
    # 3-month retention threshold to activate marketplace fee switch.
    fee_switch_retention_threshold: float = 0.38


# Primary editable assumption objects used by projection scripts.
REVENUE_ASSUMPTIONS: Final[RevenueProjectionAssumptions] = RevenueProjectionAssumptions()
MAU_ASSUMPTIONS: Final[MauProjectionAssumptions] = MauProjectionAssumptions()

# Convenience aliases.
PROJECTION_MONTHS: Final[int] = REVENUE_ASSUMPTIONS.projection_months
DEFAULT_RANDOM_SEED: Final[int] = REVENUE_ASSUMPTIONS.seed
